### ISSUE TITLE
2D similarity transform parameter map doesn't keep "CenterOfRotationPoint" parameter

### ISSUE THREAD

**Issue by NHPatterson** [InsightSoftwareConsortium/ITKElastix#93] opened 2020-12-16 02:54 UTC
Hi all, thanks for putting together this package, I'm really enjoying the ease of installation.

It seems the similarity transform as wrapped in `ITKElastix` doesn't return the `CenterOfRotationPoint` transform parameter (although it is written to file) when doing 2D to 2D registration. 

I encountered this issue using `SimpleElastix` as well so it may be in `elastix` codebase itself.

```python
import numpy as np
import itk

zero_image = np.zeros([1024,1024])

similarity_parameter_map = parameter_object.GetDefaultParameterMap("rigid")

# set method to similarity & 2D
similarity_parameter_map["Transform"] = ["SimilarityTransform"]
similarity_parameter_map["MovingImageDimension"] = ["2"]
similarity_parameter_map["FixedImageDimension"] = ["2"]

parameter_object = itk.ParameterObject.New()
parameter_object.AddParameterMap(similarity_parameter_map)

sim_result_image, sim_params = itk.elastix_registration_method(
    zero_image.astype(np.float32),
    zero_image.astype(np.float32),
    parameter_object=parameter_object,
    log_to_console=True,
    output_directory="./transforms_similarity",
)

transform_cent_rot = np.array(
    sim_params.GetParameter(0, "CenterOfRotationPoint")
).astype(np.float32)[::-1]

assert len(transform_cent_rot) == 2
```

## print(sim_params)
```cpp
ParameterObject (0000028751D7CE00)
  RTTI typeinfo:   class elastix::ParameterObject
  Reference Count: 1
  Modified Time: 2007229
  Debug: Off
  Object Name: 
  Observers: 
    none
ParameterMap 0: 
  (CenterOfRotationPoint)
  (CompressResultImage "false")
  (DefaultPixelValue 0)
  (Direction 1 0 0 1)
  (FinalBSplineInterpolationOrder 3)
  (FixedImageDimension 2)
  (FixedInternalImagePixelType "float")
  (HowToCombineTransforms "Compose")
  (Index 0 0)
  (InitialTransformParametersFileName "NoInitialTransform")
  (MovingImageDimension 2)
  (MovingInternalImagePixelType "float")
  (NumberOfParameters 4)
  (Origin 0 0)
  (ResampleInterpolator "FinalBSplineInterpolator")
  (Resampler "DefaultResampler")
  (ResultImageFormat "nii")
  (ResultImagePixelType "float")
  (Size 1024 1024)
  (Spacing 1 1)
  (Transform "SimilarityTransform")
  (TransformParameters 1 0 0 0)
  (UseDirectionCosines "true")

```

## file on disk
```cpp
(Transform "SimilarityTransform")
(NumberOfParameters 4)
(TransformParameters 1.000000 0.000000 0.000000 0.000000)
(InitialTransformParametersFileName "NoInitialTransform")
(UseBinaryFormatForTransformationParameters "false")
(HowToCombineTransforms "Compose")

// Image specific
(FixedImageDimension 2)
(MovingImageDimension 2)
(FixedInternalImagePixelType "float")
(MovingInternalImagePixelType "float")
(Size 1024 1024)
(Index 0 0)
(Spacing 1.0000000000 1.0000000000)
(Origin 0.0000000000 0.0000000000)
(Direction 1.0000000000 0.0000000000 0.0000000000 1.0000000000)
(UseDirectionCosines "true")

// SimilarityTransform specific
(CenterOfRotationPoint 511.5000000000 511.5000000000)

// ResampleInterpolator specific
(ResampleInterpolator "FinalBSplineInterpolator")
(FinalBSplineInterpolationOrder 3)

// Resampler specific
(Resampler "DefaultResampler")
(DefaultPixelValue 0.000000)
(ResultImageFormat "nii")
(ResultImagePixelType "float")
(CompressResultImage "false")
```

**Comment by N-Dekker** [comment] 2020-12-21 14:04
@NHPatterson Thanks for reporting this issue, Heath. Stefan (@stefanklein), Viktor (@ViktorvdValk) and I just discussed the issue. It appears that `elastix::SimilarityTransformElastix` should override `CreateTransformParametersMap`, in order to fix this issue. I will try to fix it soon!

**Comment by ViktorvdValk** [comment] 2020-12-22 10:45
The same counts for AffineDTITransform

**Comment by N-Dekker** [comment] 2020-12-22 11:43
> The same counts for AffineDTITransform, see issue 366 on elastix repo

Thanks @ViktorvdValk I just assigned issue https://github.com/SuperElastix/elastix/issues/366 to myself 😄

**Comment by N-Dekker** [comment] 2020-12-22 21:06
@stefanklein @ViktorvdValk I think this issue should be fixed by https://github.com/SuperElastix/elastix/pull/379  But then, what about the following three elastix transform types?
 - `AdvancedAffineTransformElastix`
 - `AffineLogTransformElastix`
 - `EulerStackTransform`

Are these three fine, or should they get a similar fix?  Is it possible to check that in Python?

**Comment by stefanklein** [comment] 2020-12-22 21:56
Hi Niels,
Potentially these could suffer from the same problem. You could see it by verifying if they have a CreateTransformParameterMap function, and compare that implementation to the WriteTransformParameterFile code.
Potentially, any transform that saves some transform specific settings (not just CenterOfRotationPoint) to a TransformParameter file (in the function WriteTransformParameterFile) could suffer from this problem when the CreateTransformParameterMap function is not in sync.
Best, Stefan

**Comment by ViktorvdValk** [comment] 2020-12-23 09:36
@N-Dekker I checked all the transforms in python and the same happens for:
- AffineLogStackTransform
- AffineLogTransformElastix
- EulerStackTransform

AdvancedAffineTransformElastix is just the AffineTransform which does return the CenterOfRotationPoint

**Comment by N-Dekker** [comment] 2020-12-23 09:48
@ViktorvdValk Do you mean that those three transforms (AffineLogStackTransform, AffineLogTransformElastix, EulerStackTransform) also need to be fixed (the same like Similarity and AffineDTI)?

**Comment by ViktorvdValk** [comment] 2020-12-23 10:34
Yes, to be certain, you check this with the verification Stefan mentioned, but if I print the output of one of these transforms, it doesn't contain the 'CenterOfRotationPoint' parameter.

**Comment by N-Dekker** [comment] 2021-01-05 20:02
@NHPatterson Hi Heath! I'm closing the issue now, as I think we got it fixed 😃  By pull request https://github.com/SuperElastix/elastix/pull/379 "Add missing parameters to transform parameter maps", which is just merged onto the https://github.com/SuperElastix/elastix develop branch. If you have the time, please check it out! And of course, if you think the issue is not entirely fixed, please feel free to reopen the issue, or submit another one. Thanks again!

**Closed by N-Dekker** 2021-01-05 20:02 UTC
